const constants = {
    ADD_MESSAGE: "ADD_MESSAGE",
    CLEAR_MESSAGE: "CLEAR_MESSAGE",
    FETCHER_LOGIN_TOGGLE: "FETCHER_LOGIN_TOGGLE",
    USER_SET_DATA: "USER_SET_DATA",
    USER_REMOVE_DATA: "USER_REMOVE_DATA",
    USER_SET_TOKEN: "USER_SET_TOKEN",
    USER_REMOVE_TOKEN: "USER_REMOVE_TOKEN"
};

export default constants;
